### ISSUE TITLE
Clarify where the activity should be

### ISSUE THREAD

**Issue by marclaporte** [PHPIDS/PHPIDS#13]
Code:
https://svn.itratos.de/svn/php-ids/ or https://github.com/PHPIDS/PHPIDS

Issues/bugs/tasks/wishes:
https://dev.itratos.de/projects/php-ids/ or https://github.com/PHPIDS/PHPIDS/issues?state=open

M ;-)

**Comment by marclaporte** [comment]
And then, answer this person: https://phpids.org/2011/03/30/we-are-back/#comment-1545

**Comment by lstrojny** [comment]
SVN link removed, GitHub added.
