### ISSUE TITLE
Publish news about Tiki adopting PHPIDS when Tiki10 is released (November 2012)

### ISSUE THREAD

**Issue by marclaporte** [PHPIDS/PHPIDS#14]
Something like this:
http://forum.itratos.de/showthread.php?37550-PHPIDS-now-part-of-Tiki-Wiki-CMS-Groupware-(tiki.org)

Another example:
https://phpids.org/2009/09/02/phpids-for-typo3/

**Comment by marclaporte** [comment]
Closing for now, as PHPIDS was removed, but I hope we can get it back in soon.

**Comment by staabm** [comment]
@marclaporte can you elaborate more why it was removed?
