### ISSUE TITLE
Set up an Ohloh.net banner somewhere

### ISSUE THREAD

**Issue by marclaporte** [PHPIDS/PHPIDS#15]
Hi!

So to get a better ranking here: https://www.ohloh.net/tags/ids

We should use: https://www.ohloh.net/p/phpids/widgets

This is why it's important:
http://info.tiki.org/article168-Support-Tiki-and-your-favorite-Free-Open-Source-projects-on-Ohloh-net

Best regards,

M ;-)

**Comment by lstrojny** [comment]
Would include it in the README of the GIT project but unfortunately it’s all JavaScript, so no luck. Won’t do it for now.
