### ISSUE TITLE
Broken unit tests

### ISSUE THREAD

**Issue by jayzeng** [PHPIDS/PHPIDS#29]
Current unit tests are broken. Going to fix them before refactoring existing code:

```
[jay] /var/www/git/PHPIDS] (master)>  phpunit -c phpunit.xml.dist 
PHPIDS TestSuite configuration:

Filter type:            xml
Filter set:             /var/www/git/PHPIDS/lib/IDS/default_filter.xml
Temporary directory:    /tmp/IDS_1360097980.7309
Configuration:          /var/www/git/PHPIDS/lib/IDS/Config/Config.ini.php

PHPUnit 3.6.10 by Sebastian Bergmann.

Configuration read from /var/www/git/PHPIDS/phpunit.xml.dist

..EE............................................................. 65 / 99 ( 65%)
..................................

Time: 01:04, Memory: 20.00Mb

There were 2 errors:

1) IDS\Tests\CachingTest::testCachingFileSetCache
Exception: Temp directory tmp/default_filter.cache seems not writable

/var/www/git/PHPIDS/lib/IDS/Caching/FileCache.php:134
/var/www/git/PHPIDS/tests/IDS/Tests/CachingTest.php:53

2) IDS\Tests\CachingTest::testCachingFileGetCache
Exception: Temp directory tmp/default_filter.cache seems not writable

/var/www/git/PHPIDS/lib/IDS/Caching/FileCache.php:134
/var/www/git/PHPIDS/tests/IDS/Tests/CachingTest.php:63

FAILURES!
Tests: 99, Assertions: 2259, Errors: 2.

Generating code coverage report, this may take a moment.
```

**Comment by kingcrunch** [comment]
Either
- Create a folder `tmp/` in the projects root or
- Copy `phpunit.xml.dist` to `phpunit.xml` and change `<var name="IDS_TEMP_DIR" value="/tmp"/>` to a existing path

**Comment by jayzeng** [comment]
Correct me if I am wrong. 
- I don't think creating a tmp/ in the projects root is a good idea. What if I download the project through composer and treat it as an external component, it limits users' ability to upgrade to a newer version of PHPIDS because the library forces users to create custom files inside the project root. 
- Second option is better, but it still requires user customization. 

What I am going to do is to create a temp file in memory by using php wrapper (php://memory or php://temp) in http://php.net/manual/en/wrappers.php.php. This way, we can even nuke the global variable in phpunit.xml. 

Thoughts?

**Comment by kingcrunch** [comment]
> I don't think creating a tmp/ in the projects root is a good idea. What if I download the project through composer and treat it as an external component, it limits users' ability to upgrade to a newer version of PHPIDS because the library forces users to create custom files inside the project root.

This is the default in `phpunit.xml.dist`. I didn't said, it's the best idea :wink: However, the folder could get versionized (like creating a `.gitkeep`-file and then set it on `.gitignore`) and then it exists on every checkout. And keep in mind: This is the _test_-default, so at least I wont use it in production, but set a custom one.

> Second option is better, but it still requires user customization.

Again: It's for the tests :wink:

> What I am going to do is to create a temp file in memory by using php wrapper (php://memory or php://temp) in http://php.net/manual/en/wrappers.php.php. This way, we can even nuke the global variable in phpunit.xml.

This doesn't work, because you can't reuse it as a pathname: Two `fopen()`-calls on `php://memory` always creates two separate streams. So you had to pass the open stream around, which isn't really comfortable in the current state.

Another solution is to use a helper library like `vfsStream`, or relying on the system temp path.
