### ISSUE TITLE
Use PHP 5.3 namespaces

### ISSUE THREAD

**Issue by lstrojny** [PHPIDS/PHPIDS#4]
- Convert code base to PHP 5.3 namespaces
- Provide a compatibility layer? (by extending the classes?)

**Comment by lgrz** [comment]
By using PHP 5.3 namespaces does this imply that the project will be 5.3+ only?

PR #20 looks like it has gone ahead and used PHP 5.3 namespaces so this issue might be resolved once PR #20 is merged?

**Comment by lstrojny** [comment]
@ampt yep, means to use 5.3 exclusively. 5.3 is really an old PHP version and should be available everywhere.

**Comment by lstrojny** [comment]
Merged
