### ISSUE TITLE
IDS\Init problem

### ISSUE THREAD

**Issue by scratcher28** [PHPIDS/PHPIDS#41]
Hi.

I am getting this error:

Catchable fatal error: Argument 1 passed to IDS\Monitor::__construct() must be an instance of IDS\Init, array given

**Comment by lstrojny** [comment]
What’s the example code to reproduce the error?

**Comment by scratcher28** [comment]
Simplified:

require_once '/vendor/autoload.php';

$request = array(
    'REQUEST' => $_REQUEST,
    'GET' => $_GET,
    'POST' => $_POST,
    'COOKIE' => $_COOKIE
);

$init = IDS\Init::init();
$ids = new IDS\Monitor($request, $init);
$result = $ids->run();

**Comment by lstrojny** [comment]
Try that:

``` php
$request = array(
    'REQUEST' => $_REQUEST,
    'GET' => $_GET,
    'POST' => $_POST,
    'COOKIE' => $_COOKIE
);

$init = IDS\Init::init();
$ids = new IDS\Monitor($init);
$result = $ids->run($request);
```

Notice that `$request` is now passed to `run()`

**Comment by scratcher28** [comment]
thanks, it works now.
