### ISSUE TITLE
How can I block a range of ip-adresses

### ISSUE THREAD

**Issue by Sepppl** [PHPIDS/PHPIDS#54]
I'm using the snippet/module for modx from Stefanie Stölting.
At the moment there are attacks comming from different IP-addresses

202.46.50.101
202.46.61.106
202.46.63.65

I would like to make only one entry to block every attack coming from 202.46._._

Is there a regular expression?

I'm not familiar with regex....

Thank you for your help.

Sepppl

**Comment by ghost** [comment]
It is very easy and documented: Just 202.46. will stop everyone from these IP ranges to go to your pages. Add a static HTML page into your Evo installation and configure PHPIDS in the module section to use this page for forwarding.

In the mask, where you can block IP addresses, you can edit the IP address and remove the last two blocks.

**Comment by ghost** [comment]
PS.: The right place to file this ticket would have been https://code.google.com/p/phpids-for-modx/issues/list

**Comment by Sepppl** [comment]
Hello Mrs Stölting,

Thank you so much for your fast reply.
I have been lost with the documentation.
That was very helpful.

Have a good day!
Hermann

Am 10.11.2013 09:30, schrieb Stefanie Janine Stölting:
